/*
--Скрипт отката
DROP TABLE CC_REQUESTS_HISTORY;
DROP TABLE CC_RESULT_TYPES;
DROP TABLE CC_USERS_ROLES_XREF;
DROP TABLE CC_USERS;
DROP TABLE CC_ROLES;
DELETE FROM SCHEMA_HISTORY 
    WHERE SCRIPT='1.0.0/V1_0_0__create_basic_tables.sql';
*/
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table CC_ROLES
--------------------------------------------------------

CREATE TABLE CC_ROLES (
    ROLE_ID INTEGER PRIMARY KEY,
    ROLE_CODE VARCHAR(10) UNIQUE NOT NULL,
    ROLE_NAME VARCHAR(20) NOT NULL
);
COMMENT ON TABLE CC_ROLES IS 'Роли для пользователей';
COMMENT ON COLUMN CC_ROLES.ROLE_ID IS 'Идентификатор роли';
COMMENT ON COLUMN CC_ROLES.ROLE_CODE IS 'Код роли';
COMMENT ON COLUMN CC_ROLES.ROLE_NAME IS 'Наименование роли';

INSERT INTO CC_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME) 
    VALUES (1, 'ADMIN', 'Администратор');
INSERT INTO CC_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME) 
    VALUES (2, 'USER', 'Пользователь');

--------------------------------------------------------
--  DDL for Table CC_USERS
--------------------------------------------------------

CREATE TABLE CC_USERS (
    USER_ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) UNIQUE NOT NULL, 
    PASSWORD VARCHAR(256) NOT NULL, 
    ENABLED BOOLEAN NOT NULL, 
    EMAIL VARCHAR(50) UNIQUE NOT NULL
 );
COMMENT ON TABLE CC_USERS IS 'Список пользователей';
COMMENT ON COLUMN CC_USERS.USER_ID IS 'Идентификатор пользователя';
COMMENT ON COLUMN CC_USERS.USERNAME IS 'Логин';
COMMENT ON COLUMN CC_USERS.PASSWORD IS 'Пароль';
COMMENT ON COLUMN CC_USERS.ENABLED IS 'Активен';
COMMENT ON COLUMN CC_USERS.EMAIL IS 'Адрес электронной почты';

CREATE UNIQUE INDEX IDX_U_USERNAME ON CC_USERS (USERNAME);
CREATE UNIQUE INDEX IDX_U_EMAIL ON CC_USERS (EMAIL);

--------------------------------------------------------
--  DDL for Table CC_USERS_ROLES_XREF
--------------------------------------------------------

CREATE TABLE CC_USERS_ROLES_XREF(
    USERS_ROLES_ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT UNIQUE NOT NULL, 
    ROLE_ID INTEGER NOT NULL
);
COMMENT ON TABLE CC_USERS_ROLES_XREF IS 'Связка пользователей и ролей';
COMMENT ON COLUMN CC_USERS_ROLES_XREF.USERS_ROLES_ID IS 'Идентификатор записи';
COMMENT ON COLUMN CC_USERS_ROLES_XREF.USER_ID IS 'Идентификатор пользователя';
COMMENT ON COLUMN CC_USERS_ROLES_XREF.ROLE_ID IS 'Идентификатор роли';

ALTER TABLE CC_USERS_ROLES_XREF ADD UNIQUE (USER_ID, ROLE_ID);
ALTER TABLE CC_USERS_ROLES_XREF ADD CONSTRAINT FK_CC_USERS_ROLES_XREF_USER_ID 
    FOREIGN KEY (USER_ID) REFERENCES CC_USERS (USER_ID);
ALTER TABLE CC_USERS_ROLES_XREF ADD CONSTRAINT FK_CC_USERS_ROLES_XREF_ROLE_ID 
    FOREIGN KEY (ROLE_ID) REFERENCES CC_ROLES (ROLE_ID);

--------------------------------------------------------
--  DDL for Table CC_RESULT_TYPES
--------------------------------------------------------

CREATE TABLE CC_RESULT_TYPES (
    RESULT_ID INTEGER PRIMARY KEY,
    RESULT_CODE VARCHAR(10) UNIQUE NOT NULL,
    RESULT_NAME VARCHAR(20) NOT NULL
);
COMMENT ON TABLE CC_RESULT_TYPES IS 'Типы результатов выполнения запроса';
COMMENT ON COLUMN CC_RESULT_TYPES.RESULT_ID IS 'Идентификатор результата';
COMMENT ON COLUMN CC_RESULT_TYPES.RESULT_CODE IS 'Код результата';
COMMENT ON COLUMN CC_RESULT_TYPES.RESULT_NAME IS 'Наименование результата';

INSERT INTO CC_RESULT_TYPES (RESULT_ID, RESULT_CODE, RESULT_NAME) 
    VALUES (1, 'SUCCESS', 'Успешно');
INSERT INTO CC_RESULT_TYPES (RESULT_ID, RESULT_CODE, RESULT_NAME) 
    VALUES (2, 'FAILURE', 'Не успешно');

--------------------------------------------------------
--  DDL for Table CC_REQUESTS_HISTORY
--------------------------------------------------------

CREATE TABLE CC_REQUESTS_HISTORY (
    REQUEST_HISTORY_ID BIGSERIAL PRIMARY KEY, 
    CREATE_TS TIMESTAMP NOT NULL, 
    USER_ID BIGINT NOT NULL, 
    IP_ADDRESS VARCHAR(15) NOT NULL, 
    URI VARCHAR(30) NOT NULL, 
    PARAMS VARCHAR(1000) NOT NULL, 
    RESULT_ID INTEGER NOT NULL, 
    RESULT_SIZE NUMERIC(18,0)
);
COMMENT ON TABLE CC_REQUESTS_HISTORY 
    IS 'История расчетов кредитного калькулятора';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.REQUEST_HISTORY_ID 
    IS 'Идентификатор итории';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.CREATE_TS IS 'Время создания записи';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.USER_ID IS 'Идентификатор пользователя';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.IP_ADDRESS IS 'IP-адрес';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.URI IS 'Идентификатор ресурса';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.PARAMS 
    IS 'Исходные параметры для расчета';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.RESULT_ID IS 'Идентификатор результата';
COMMENT ON COLUMN CC_REQUESTS_HISTORY.RESULT_SIZE 
    IS 'Размер результата в байтах';

CREATE INDEX IDX_NU_CREATE_TS ON CC_REQUESTS_HISTORY (CREATE_TS);
ALTER TABLE CC_REQUESTS_HISTORY ADD CONSTRAINT FK_CC_REQUESTS_HISTORY_USER_ID 
    FOREIGN KEY (USER_ID) REFERENCES CC_USERS (USER_ID);
ALTER TABLE CC_REQUESTS_HISTORY ADD CONSTRAINT FK_CC_REQUESTS_HISTORY_RESULT_ID 
    FOREIGN KEY (RESULT_ID) REFERENCES CC_RESULT_TYPES (RESULT_ID);
